name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: HurricanKai/Publish-Docker-Github-Action@master
    - name: Publish Snapshot to Registry
      if: !contains(github.ref, 'refs/tags/v')
      with:
        name: tarioch/fava
        snapshot: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Release to Registry
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: tarioch/fava
        tag: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        


